# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SimulatedRealitySoft.USBDDFixer
PackageVersion: '1.2'
InstallerType: portable
UpgradeBehavior: uninstallPrevious
Commands:
- usbddfix
ReleaseDate: 2024-09-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/SimulatedRealitySoft/USBDDFixer/releases/download/v1.2/USBDDFix.exe
  InstallerSha256: F6BCD7B90080C9C139AB64722F7EEA3EB73130AACBF24167A4F071A8154F96B3
ManifestType: installer
ManifestVersion: 1.12.0
