# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: SimulatedRealitySoft.USBDDFixer
PackageVersion: '1.2'
PackageLocale: en-US
Publisher: Simulated Reality Soft
PublisherUrl: https://github.com/SimulatedRealitySoft
PublisherSupportUrl: https://github.com/SimulatedRealitySoft/USBDDFixer/issues
Author: Diego Calveyra
PackageName: USBDDFixer
PackageUrl: https://github.com/SimulatedRealitySoft/USBDDFixer
License: GPL-3.0
LicenseUrl: https://github.com/SimulatedRealitySoft/USBDDFixer/blob/HEAD/LICENSE
Copyright: USB DD Fixer (c) 2024 Simulated Reality Soft
CopyrightUrl: https://github.com/SimulatedRealitySoft/USBDDFixer#license
ShortDescription: 'Description: USB DD Fixer is a software designed to restore USB drives that have been formatted or damaged by using disk imaging (Disk Dump) writing methods. This tool allows users to regain access to their USB devices quickly and easily.'
Moniker: usbddfixer
Tags:
- dd
- fix
- usb
ReleaseNotes: First stable launch
ReleaseNotesUrl: https://github.com/SimulatedRealitySoft/USBDDFixer/releases/tag/v1.2
ManifestType: defaultLocale
ManifestVersion: 1.12.0
