# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Baltram.seednaut
PackageVersion: 0.1.1
PackageLocale: en-US
Publisher: Baltram
PublisherUrl: https://github.com/Baltram
PublisherSupportUrl: https://github.com/Baltram/seednaut/issues
PackageName: seednaut
PackageUrl: https://github.com/Baltram/seednaut
License: Apache-2.0
ShortDescription: Inspect, verify and extract files from Seedvault backups.
Moniker: seednaut
Tags:
- android
- backup
- calyxos
- cli
- cryptography
- e-os
- grapheneos
- lineageos
- rust
- tui
ReleaseNotes: This release removes the Protocol Buffers compiler build dependency. Building from source and cargo install seednaut no longer require protoc.
ReleaseNotesUrl: https://github.com/Baltram/seednaut/releases/tag/v0.1.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
