# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Baltram.seednaut
PackageVersion: 0.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: seednaut-v0.1.1-x86_64-pc-windows-msvc/seednaut.exe
  PortableCommandAlias: seednaut
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-05-19
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Baltram/seednaut/releases/download/v0.1.1/seednaut-v0.1.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: 98E2B3D892BE6DAB02E5EE16384936EDA82BF44E66B8E64F1BC10965B332C78E
ManifestType: installer
ManifestVersion: 1.12.0
